### ISSUE TITLE
Tests.

### ISSUE THREAD

**Issue by jobala** [kjagoo/Bucketlist#4]
At the moment, the tests does not use  determinative database, ie 
when running new tests, the database contains data from the previous time the tests were run.

To use a predictable database,

- dropdb before test,

- createdb,

- seed the database

**Comment by kjagoo** [comment]
To use a predictable database,

dropdb before test,

createdb, :https://github.com/kjagoo/Bucketlist/pull/1/commits/aa6104feaa4a9ec90ea2b5492bfc2474054f59a8

seed the database :https://github.com/kjagoo/Bucketlist/pull/1/commits/f14523772dc8b565254d559d67b5c1ba7371aabe
