### ISSUE TITLE
API Routes.

### ISSUE THREAD

**Issue by jobala** [kjagoo/Bucketlist#5]
**Authentication**
Email validation:
Users can be registered with invalid format emails.
Return auth token on successful register with response

JWT token:
Put more user information in the token rather than just the user id.

Make bucketlist titles unique

**Comment by kjagoo** [comment]
1. response for token in https://github.com/kjagoo/Bucketlist/commit/3fd187acf892d1908e1cc89b9c1a1d9368ea20c3

2. Return auth token on successful register with response ; done 

3. Email validation: https://github.com/kjagoo/Bucketlist/commit/06d863edf6226224cff862d15cc7dc7bab2a2c3d

4. Make bucketlist titles unique : https://github.com/kjagoo/Bucketlist/commit/f561ae22cc3d824c875b400745595eedb2ee35b2
